name: Go
on:
  push:
    tags: [ 'v*.*.*' ]
    branches: [ "main" ]
  pull_request:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Vet
      run: go vet ./...
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      if: startsWith(github.ref, 'refs/tags/')
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
